# Generated by Django 4.2.6 on 2023-10-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Student'), (1, 'Teacher'), (2, 'Admin')]),
        ),
    ]
