# Generated by Django 4.2.6 on 2023-10-19 17:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='owner',
            field=models.ManyToManyField(related_name='owner_courses', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
